set shell := ["sh", "-c"]
name := "minimal"

build:
    cargo build
    if [ -z target/powerpc-unknown-eabi/debug/rogue.elf ]; then rm target/powerpc-unknown-eabi/debug/{{name}}.elf; fi;
    cp target/powerpc-unknown-eabi/debug/{{name}} target/powerpc-unknown-eabi/debug/{{name}}.elf

run: build
    dolphin-emu -e target/powerpc-unknown-eabi/debug/{{name}}.elf
