[package]
name = "ogc-engine"
version = "0.1.0"
authors = ["Knarkzel"]
edition = "2021"

[dependencies]
embedded-graphics = "0.7"

[dev-dependencies]
tinytga = "0.4.1"
profont = "0.5.0"

[dependencies.ogc-rs]
path = "./ogc-rs"
features = ["ffi"]
