[package]
name = "ogc-rs"
version = "0.7.1"
authors = ["rust-wii"]
edition = "2018"

[lib]
crate-type = ["rlib"]
name = "ogc"

[dependencies]
bitflags = "1.2"
libc = "0.2"
num_enum = { version = "0.5", default-features = false }
ogc-sys = { path = "ogc-sys" }

[features]
ffi = []
